server:
  port: 9000
  
spring:
  cloud:
    gateway:
      routes:
      - id: creditcardservice  #route identification
        uri: http://localhost:8095/
        predicates:
        - Path=/api/banking/creditcard/**
        
       
      - id: userservice  #route identification
        uri: http://localhost:8096/
        predicates:
         - Path=/api/banking/user/** 